name: User_permission
values:
  - key: base_url
    value: ""
    enabled: true
  - key: user_token
    value: ""
    enabled: true
  - key: user_id
    value: ""
    enabled: true
  - key: user_name
    value: ""
    enabled: true
  - key: user_refesh_token
    value: ""
    enabled: true
color: null
